#!/bin/bash
export Cellar=$(brew --cellar socios)

#Installation of VirtualBox

function init {
	source $Cellar/*/lib/install_virtualbox.scpt
}

#Building VirtualBox_VM

function createvm {
	source $Cellar/*/lib/create_vm.sh
}

#Uninstalling VirtualBox_VM

function unmount {
	source $Cellar/*/lib/disk_partition.sh
}

#Uninstalling VirtualBox_VM

function purge {
	source $Cellar/*/lib/purge.sh
}

#Display Help_Menu

function help {
	echo "Socios - Linux with your Mac."
	echo "build          Create the virtual machine in VirtualBox"
	echo "init           Check the environment to install Socios"
	echo "--help         Print this Help menu"
	echo "--version      Print the current version"	
	echo "unmount         unmount the current disk space in MAC Machine"
	echo "purge           Uninstall the Virtualbox and GDisk"
}

#Version of Socios formula

function version {
	tag=$(brew info socios | awk '/stable/ {print $3}' | sed 's/^/v/')
	echo "$tag"
}

########################################
#Socios options passing with Arguments #
########################################

for arg in "$@"; do
  if [[ "$arg" = init ]]; then
	init
  fi
  if [[ "$arg" = build ]]; then
	createvm
  fi
  if [[ "$arg" = --help ]]; then
	help
  fi
  if [[ "$arg" = --version ]]; then
	version
  fi
  if [[ "$arg" = unmount ]]; then
	unmount
  fi
  if [[ "$arg" = purge ]]; then
	purge
  fi
done
########################################
